# Generated by Django 5.2 on 2025-04-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramen_name', models.CharField(max_length=40)),
                ('image_url', models.CharField(max_length=800)),
                ('like_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ramen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramen.ramen')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramen.user')),
            ],
        ),
    ]
